language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t gustavomoreirapt/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true gustavomoreirapt/docker-react npm run test